alexfalkowski/nonnative

Gemfile.lock
features/support/env.rb
lib/nonnative.rb
lib/nonnative/version.rb

bug: fix typo in code.

---

Gemfile.lock
README.md
features/support/bin/start
features/support/echo_client.rb
features/support/echo_server.rb
lib/nonnative/port.rb
lib/nonnative/version.rb

feat: use localhost

---

Gemfile.lock
Makefile
nonnative.gemspec

Reason https://jira.sonarsource.com/browse/SONARSLANG-477

build: downgrade simplecov

---

lib/nonnative/grpc_server.rb
lib/nonnative/http_server.rb

fix: add comments

---

.rubocop.yml
Gemfile.lock
README.md
features/servers.yml
features/step_definitions/servers_steps.rb
lib/nonnative.rb
lib/nonnative/chaos_proxy.rb
lib/nonnative/configuration.rb
lib/nonnative/configuration_process.rb
lib/nonnative/configuration_proxy.rb
lib/nonnative/configuration_server.rb
lib/nonnative/proxy_factory.rb
lib/nonnative/server.rb
lib/nonnative/service.rb
nonnative.gemspec

feat: move to use predefined port

---

Gemfile.lock
README.md
features/support/grpc_server.rb
lib/nonnative/grpc_server.rb
lib/nonnative/version.rb

fix(grpc): make servers consistent

---

.rubocop.yml
Gemfile.lock
Makefile
features/step_definitions/servers_steps.rb
lib/nonnative/chaos_proxy.rb
lib/nonnative/pool.rb
lib/nonnative/version.rb

- Start servers first
- Ignore ECONNRESET
- Make sure starting multiple servers works.

bug: start servers first

---

Gemfile.lock
lib/nonnative/pool.rb
lib/nonnative/version.rb

Make sure we process processes and servers in order.

feat: process start and stop in order 

---

Gemfile.lock
features/servers.feature
features/step_definitions/servers_steps.rb
lib/nonnative.rb
lib/nonnative/chaos_proxy.rb
lib/nonnative/pool.rb
lib/nonnative/server.rb
nonnative.gemspec

This is the beginning of our chaos journey. The proxy will be able handle all sorts of failures.

feat: add ability to create chaos

---

lib/nonnative/chaos_proxy.rb

fix: sync state

---

.rubocop.yml
README.md
features/step_definitions/servers_steps.rb
lib/nonnative/configuration.rb
lib/nonnative/configuration_server.rb

refactor(proxy): make consistent

---

.rubocop.yml
Gemfile.lock
README.md
features/step_definitions/servers_steps.rb
lib/nonnative/chaos_proxy.rb
lib/nonnative/configuration.rb
lib/nonnative/configuration_proxy.rb
lib/nonnative/configuration_server.rb
lib/nonnative/delay_socket_pair.rb
lib/nonnative/socket_pair.rb
lib/nonnative/version.rb

Pass options so we can control the delay time.

feat: pass options to socket pair

---

.rubocop.yml
Gemfile.lock
README.md
features/processes.feature
features/processes.yml
features/servers.feature
features/servers.yml
features/step_definitions/processes_steps.rb
features/step_definitions/servers_steps.rb
features/support/http_server.rb
lib/nonnative/command.rb
lib/nonnative/configuration.rb
lib/nonnative/configuration_process.rb
lib/nonnative/configuration_server.rb
lib/nonnative/grpc_server.rb
lib/nonnative/http_server.rb
lib/nonnative/version.rb

feat: add logging to servers

---

features/servers.feature
features/step_definitions/servers_steps.rb

test: grpc faults

---

Gemfile.lock
README.md
lib/nonnative.rb
lib/nonnative/go_command.rb
lib/nonnative/version.rb

Add the ability to generate a go command.

feat: add running go command

---

README.md

feat: remove badge from docs

---

.rubocop.yml
Gemfile.lock
README.md
features/command.feature
features/step_definitions/command_steps.rb
lib/nonnative.rb
lib/nonnative/go_command.rb
lib/nonnative/version.rb

Rather than expose the type we add it to the main entry point.

feat: simplify go exeutable

---

Gemfile.lock
lib/nonnative/close_all_socket_pair.rb
lib/nonnative/fault_injection_proxy.rb
lib/nonnative/socket_pair.rb
lib/nonnative/socket_pair_factory.rb
lib/nonnative/version.rb

Make sure we close the connections when we change state

feat: terminate connections on change

---

Gemfile.lock
features/support/tcp_server.rb
lib/nonnative/fault_injection_proxy.rb
lib/nonnative/version.rb

Make sure we see what errors occur during interruptions

feat: log interruptions

---

README.md

Update example to include build tags.

docs: update go example

---

Gemfile.lock
README.md
features/command.feature
features/configs/go.yml
features/configs/servers.yml
features/processes.feature
features/step_definitions/command_steps.rb
features/step_definitions/processes_steps.rb
features/support/bin/start
lib/nonnative.rb
lib/nonnative/configuration.rb
lib/nonnative/version.rb
nonnative.gemspec

Here are the changes:
- As programatically the config can get quite big, we can use a YAML file. We added the support to create a go command.
- Allow getting logs from a file.
- Rename from klass to class in config.

feat: add loading go command through config

---

Gemfile.lock
README.md
features/step_definitions/benchmark_steps.rb
features/step_definitions/command_steps.rb
features/step_definitions/servers_steps.rb
features/step_definitions/services_steps.rb
lib/nonnative.rb
lib/nonnative/configuration.rb
lib/nonnative/version.rb

Load config file through configure
```ruby
Nonnative.configure do |config|
config.load_file('configuration.yml')
end
```

feat: add loading config through configure

---

.rubocop.yml
Gemfile.lock
README.md
features/configs/processes.yml
features/step_definitions/benchmark_steps.rb
features/step_definitions/processes_steps.rb
lib/nonnative/configuration.rb
lib/nonnative/configuration_process.rb
lib/nonnative/configuration_runner.rb
lib/nonnative/configuration_server.rb
lib/nonnative/process.rb
lib/nonnative/runner.rb
lib/nonnative/server.rb
lib/nonnative/version.rb

Allow passing env variables for processes.

feat: allow to pass env variables to processes

---

Gemfile.lock
features/servers.feature
features/step_definitions/servers_steps.rb
features/support/http_server.rb
lib/nonnative/observability.rb
lib/nonnative/version.rb
nonnative.gemspec

Add ability to test for liveness and readiness.

feat(observability): add liveness and readiness

---

Gemfile.lock
lib/nonnative/process.rb
lib/nonnative/version.rb

fix(process): use key for env

---

.rubocop.yml
Gemfile.lock
features/command.feature
features/step_definitions/command_steps.rb
lib/nonnative.rb
lib/nonnative/go_command.rb
lib/nonnative/version.rb

Make sure we generate unique file names for go command. This way we can merge things.

feat(go): make sure we generate a unique file

---

Gemfile.lock
README.md
features/step_definitions/command_steps.rb
features/step_definitions/processes_steps.rb
lib/nonnative/configuration.rb
lib/nonnative/process.rb
lib/nonnative/version.rb

Make sure we recreate the command with every execution.

fix(command): make sure we recreate with every execution

---

Gemfile.lock
README.md
features/support/no_stop_server.rb
features/support/tcp_server.rb
lib/nonnative/fault_injection_proxy.rb
lib/nonnative/grpc_server.rb
lib/nonnative/http_server.rb
lib/nonnative/no_proxy.rb
lib/nonnative/port.rb
lib/nonnative/version.rb

Forgot to use host everywhere.

fix: use host

---

Gemfile.lock
features/processes.feature
features/step_definitions/processes_steps.rb
lib/nonnative/configuration.rb
lib/nonnative/cucumber.rb
lib/nonnative/version.rb

feat: allow checking logs

---

.github/dependabot.yml

ci: add dependabot file

---

Gemfile.lock
lib/nonnative/version.rb

feat(cucumber): update to v8

---

.circleci/config.yml
Gemfile.lock
README.md
features/configs/servers.yml
features/configs/services.yml
features/step_definitions/processes_steps.rb
features/step_definitions/servers_steps.rb
features/step_definitions/services_steps.rb
lib/nonnative/configuration.rb
lib/nonnative/configuration_proxy.rb
lib/nonnative/configuration_runner.rb
lib/nonnative/proxy_factory.rb
lib/nonnative/socket_pair_factory.rb
lib/nonnative/version.rb

feat: rename to kind

---

Gemfile.lock
features/support/http_server.rb
lib/nonnative/observability.rb
lib/nonnative/version.rb

Follow names as described in https://kubernetes.io/docs/reference/using-api/health-checks/

feat(observability): change endpoints

---

Gemfile.lock
README.md
features/configs/go.yml
features/step_definitions/command_steps.rb
lib/nonnative.rb
lib/nonnative/configuration.rb
lib/nonnative/go_command.rb
lib/nonnative/version.rb

This change will allow to limit the number of files the go command generates.

feat(command): add tools to go command

---

Gemfile.lock
lib/nonnative/version.rb
nonnative.gemspec

https://github.com/zombocom/get_process_mem/compare/v0.2.7...v1.0.0
https://github.com/zombocom/get_process_mem/blob/main/CHANGELOG.md#100

feat(deps): upgraded get_process_mem (1.0.0)

---

Gemfile.lock

https://rubygems.org/gems/bundler/versions/2.6.1

test(deps): upgraded bundler to 2.6.1

---

.circleci/config.yml

https://github.com/alexfalkowski/docker/pull/585

build(ci): update ruby:1.3

---

.circleci/config.yml

https://github.com/alexfalkowski/docker/pull/590

build(ci): update ruby:1.5

---

.rubocop.yml
Gemfile.lock
README.md
features/configs/go.yml
features/configs/processes.yml
features/configs/servers.yml
features/configs/services.yml
features/step_definitions/servers_steps.rb
features/support/tcp_server.rb
lib/nonnative.rb
lib/nonnative/configuration.rb
lib/nonnative/cucumber.rb
lib/nonnative/http_server.rb
lib/nonnative/version.rb

Running returns an integer so we have to check that.

feat(http_server): handle shutdown correctly

---

.circleci/config.yml

https://github.com/alexfalkowski/docker/pull/594

build(ci): update alexfalkowski/ruby:1.6

---

Gemfile.lock
features/processes.feature
features/servers.feature
features/services.feature
lib/nonnative.rb
lib/nonnative/cucumber.rb
lib/nonnative/fault_injection_proxy.rb
lib/nonnative/no_proxy.rb
lib/nonnative/pool.rb
lib/nonnative/version.rb

feat(proxy): add ability to reset proxies

---

Gemfile.lock
README.md
features/configs/go.yml
features/configs/processes.yml
features/configs/servers.yml
features/configs/services.yml
features/step_definitions/benchmark_steps.rb
features/step_definitions/processes_steps.rb
features/step_definitions/servers_steps.rb
features/step_definitions/services_steps.rb
lib/nonnative.rb
lib/nonnative/configuration.rb
lib/nonnative/go_command.rb
lib/nonnative/port.rb
lib/nonnative/process.rb
lib/nonnative/version.rb

This will allow to diagnose issues.

feat(logger): add logging

---

Gemfile.lock
lib/nonnative.rb
lib/nonnative/version.rb

This will allow us to dynamically apply condtions to servers, etc.

feat(clear): separate clearing pool or configuration
